// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WPA.backend.Helpers;

namespace WPA.backend.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20200219175704_addedPlannerId")]
    partial class addedPlannerId
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WPA.backend.Entities.Planner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CeremonyDate");

                    b.Property<string>("CeremonyPlace");

                    b.Property<DateTime>("WeddingDate");

                    b.Property<string>("WeddingPlace");

                    b.HasKey("Id");

                    b.ToTable("Planners");
                });

            modelBuilder.Entity("WPA.backend.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<byte[]>("PasswordHash");

                    b.Property<byte[]>("PasswordSalt");

                    b.Property<int>("PlannerId");

                    b.Property<string>("Username");

                    b.HasKey("Id");

                    b.HasIndex("PlannerId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("WPA.backend.Entities.User", b =>
                {
                    b.HasOne("WPA.backend.Entities.Planner", "Planner")
                        .WithMany()
                        .HasForeignKey("PlannerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
